name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: CI
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
      - name: Build
        run: cargo build
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Formatter
        run: cargo fmt --check

  tests:
    name: Unit/integration tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
      - run: cargo test

  build_release:
    name: Compile release build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
      - run: cargo build --release